// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eescqavnubzgjwgoxehv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlc2NxYXZudWJ6Z2p3Z294ZWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzk2MzMsImV4cCI6MjA2MDg1NTYzM30.gTKBrML0SN_lhKiXPgpcUrhNW3RmWruEx3Kh7Arwbu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);